### ISSUE TITLE
Add link option

### ISSUE THREAD

**Issue by grandeljay** [EssentialBlocks/slider-block#10]
Hello,

I think it would be very useful if there was an option to add the image url as a link so lightbox plugins can enlarge a slide image. 

Alternatively any other solution that allows the user to enlarge the slide would be lovely.

Edit: I found a fix but was unable to clone your repository. There seems to be some kind of symbolic link or submodule in it. Please consider fixing this. Here is what I used to make the links work:

```css
.slick-slide.slick-active.slick-current {
    z-index: 1;
}
```
